### ISSUE TITLE
Using my own database

### ISSUE THREAD

**Issue by bonchae** [dlatk/dlatk#10]
I've installed dlatk-docker. Is there any instruction available to use my own database, instead of dla_tutorial? I've tried a number of options found from https://hub.docker.com/_/mysql/, but no success so far. Thanks for making this tool available to use!

**Comment by bonchae** [comment]
I think I figured it out.

**Comment by sjgiorgi** [comment]
You can point to any database using the `-d` flag. Info [here](http://dlatk.wwbp.org/fwinterface/fwflag_d.html).

**Comment by bonchae** [comment]
Thanks!
