### ISSUE TITLE
dlatk_lexicon.sql

### ISSUE THREAD

**Issue by bonchae** [dlatk/dlatk#11]
I am going through the tutorial documentation. 

One document (https://dlatk.wwbp.org/install.html) says there should be sql file (dlatk_lexicon.sql) in the data folder. Another document (https://dlatk.wwbp.org/tutorials/tut_docker.html) indicates a different sql file name (permaLexicon.sql). The data folder contains permaLexicon.sql

The tutorial (https://dlatk.wwbp.org/tutorials/tut_dla.html) also uses a sql statement like "select * from dlatk_lexicon.met_a30_2000_cp limit 10;"

Where can I find dlatk_lexicon.sql?

Thanks!

**Comment by sjgiorgi** [comment]
Sorry for this confusion. Looks like the documentation is ahead of what is actually pushed to pip/docker. 

`permaLexicon` and `dlatk_lexicon` *should* contain the same tables/data and DLATK should point to this database automatically. The only thing you will need to change are the manual sql commands.
