### ISSUE TITLE
Wordcloud commands in tutorial creating .txt files but not .png files

### ISSUE THREAD

**Issue by tgrover2** [dlatk/dlatk#13]
I'm trying to run the command in the DLA tutorial to create the wordclouds for the n-gram correlations using this command: 

`dlatkInterface.py -d dla_tutorial -t msgs_xxx -c user_id \
-f 'feat$1to3gram$msgs_xxx$user_id$16to16$0_05' \
--outcome_table blog_outcomes  --group_freq_thresh 500 \
--outcomes age gender --output_name xxx_output \
--tagcloud --make_wordclouds`

The command runs fine, but when it is finished, the resulting files (ie. age_pos, age_neg etc.) are just .txt files, and the .png files do not appear anywhere in my system even though the output says they were generated. 

Any idea what could be going on for .txt files to be generated rather than .png files?

I have the python wordcloud package installed, and I've changed the line in wordcloud.py to `wordcloud_algorithm='amueller'` as instructed in the installation instructions.

**Comment by sjgiorgi** [comment]
What version of `wordcloud` is installed?

**Comment by tgrover2** [comment]
Version 1.4.1 is installed

**Comment by tgrover2** [comment]
Any idea what the issue might be?

**Comment by sjgiorgi** [comment]
How did you install DLATK?

**Comment by ashleygw** [comment]
No idea if this is still relevant, but this is exactly what I experienced when I made this issue. #9 Unless DLATK updated the way they pass in the data to the amueller module, it will not work. If you can downgrade the wordcloud module you are using it may work, or you can make the changes I described in the issue.

**Comment by sjgiorgi** [comment]
We us an older version of `wordcloud`, please use version 1.1.3.
