### ISSUE TITLE
Extracting extra-linguistic features?

### ISSUE THREAD

**Issue by bwang482** [dlatk/dlatk#16]
Hi there, thanks for the library!
I have a small number of dialogue text data and I want to classify them to binary classes. I wanted to use dlatk to extract extract extra-linguistic features such as personality traits but please correct me if I am wrong I only see it extracts ngrams and topic proportion as features? 

If it is indeed possible to extract extract extra-linguistic features, where should I start? I want to use it as functions in my data pipeline not as in command line. Sorry for the very general questions, it'd be great if you can provide any advices! Thanks very much!

**Comment by hschwartz** [comment]
Hello,

Yes it is possible to extract predicted user attributes given their
language. Our personality models are not publicly available (not our choice
but the data owners). However, there are plenty of other models and lexica
for other attributes.

To get started I suggest I suggest
1) The dlatk getting started tutorial:
https://dlatk.wwbp.org/tutorials/tut_dla.html

2) age and gender lexicon tutorial: https://youtu.be/bCsnyhImX0s

3) "intro predictive / classification / lexica" here:
https://dlatk.wwbp.org/tutorials.html

You can find other lexica here:
http://wwbp.org/lexica.html


-Andy

**Comment by bwang482** [comment]
Thanks very much for your reply Andrew! It says [here](http://wwbp.org/lexica.html ) that one needs to request you for a refined lexica such as LIWC. May I do so here or do you prefer an email? 

I also found [here](http://wwbp.org/data.html) that there are Word and Phrase Correlations for the five big personalities. Perhaps one can use these lexicons for estimating ones personality from its messages or conversations, instead of your trained personality models as they are not available. What do you think? Thanks again for your kind help.
