### ISSUE TITLE
tutorial: ERROR 1049 (42000): Unknown database 'dla_tutorial'

### ISSUE THREAD

**Issue by hugokitano** [dlatk/dlatk#17]
Hi, I just installed mysql and dlatk. I was able to open up mysql and terminal but the first line of the tutorial "USE dla_tutorial;" failed with the above error. I was able to import dlatk into python and submit the command "dlatkInterface.py" and get its manual page, so it might be a problem with the MySQL? Thanks!

Hugo

**Comment by sjgiorgi** [comment]
You have to load the packages sql files to MySQL:

```
mysql -u username -p  < /path/to/dlatk/data/dla_tutorial.sql
mysql -u username -p  < /path/to/dlatk/data/dlatk_lexica.sql
```
