### ISSUE TITLE
dlatk.messageAnnotator file missing from pip installation (version 1.1.6)

### ISSUE THREAD

**Issue by tgrover2** [dlatk/dlatk#19]
I had to try and reinstall a newer version of DLATK because for some reason the source code I had was not recognizing the arguments '-m' and '--create-dists' for creating the readable distributions on messages when following the steps for the Mallet topic modeling tutorial: see [step #7](https://dlatk.wwbp.org/tutorials/tut_lda.html). I'm not sure why this is the case? I checked the source code that I had at this time and there was no mention of these arguments anywhere in the code that I could find.

However, I tried uninstalling my dlatk version and reinstalling through pip ('sudo pip install dlatk'), it installed fine, but when I tried to run any commands I was getting an error that dlatk.messageAnnotator could not be found. I did not see the file anywhere in the source code. Is this normal?

**Comment by sjgiorgi** [comment]
I've updated the pip install to include this file, please try again.
