### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by ashishkab0b** [dlatk/dlatk#23]
I am installing dlatk from pip on OSX 10.15.17. The installation fails as it tried to install scikit-learn==0.18.2. I've tried pre-installing a newer version of sklearn, but it will uninstall the newer version and try to install this previous broken version. 
Here is the error:
`error: Command "clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/Users/ashish/files/research/dlatk_reappraisal/venv/lib/python3.9/site-packages/numpy/core/include -I/Users/ashish/files/research/dlatk_reappraisal/venv/lib/python3.9/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/ashish/files/research/dlatk_reappraisal/venv/include -I/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c sklearn/cluster/_dbscan_inner.cpp -o build/temp.macosx-10.15-x86_64-3.9/sklearn/cluster/_dbscan_inner.o -MMD -MF build/temp.macosx-10.15-x86_64-3.9/sklearn/cluster/_dbscan_inner.o.d" failed with exit status 1
`

**Comment by sjgiorgi** [comment]
Do you have numpy installed? Can you run 

`pip freeze | grep numpy`

and report the version number?

**Comment by ashishkab0b** [comment]
Yes. My numpy version is numpy==1.19.4.

Thanks.

**Comment by sjgiorgi** [comment]
It looks like scikit-learn isn't supported for Python 3.9. 

https://github.com/scikit-learn/scikit-learn/issues/18621

Your specific error goes back to Python 3.7, with some cython issues: 

https://github.com/scikit-learn/scikit-learn/issues/11320

Are you able to use python 3.5 or 3.6?

**Comment by ashishkab0b** [comment]
Thanks for looking into this. I don't have any python 3.0-3.6 installed and I ended up implementing the analysis using other packages so I will close the issue. 

FYI I have installed and am able to use a newer version of sklearn (scikit-learn==0.23.2). The problem seems to be that the pip installation of dlatk is trying to roll back to an old version of sklearn from 2016. Maybe at some point you might update the pip deployment to be compatible with a newer version of sklearn? 

Anyway, thanks again for your help!

**Comment by earissola** [comment]
Hi @amehtaSF, I know that you closed the issue, but maybe it can useful for the future. I run on the same issue as you (even same OS). After some research (and mirroring the Docker provided by the developers), I managed to make the software to work. To do so, I installed python 3.6.6, using **pyenv** (to be able to have different versions of the python interpreter installed). Then, I installed these packages taking care of their versions (which otherwise could cause compatibility issues at installation time, as you faced). I recommend to put this information in a txt file and run ```$ pip install -r FILENAME```

```
numpy==1.14.5
pandas==0.23.3
scikit-learn==0.19.1
scipy==1.1.0
statsmodels==0.9.0
matplotlib==2.2.2
mysqlclient==1.3.13
SQLAlchemy==1.2.9
Pillow==5.2.0
pytz==2018.5
Django==2.0.7
dlatk==1.1.4
nltk==3.3
wordcloud==1.1.3
textstat==0.4.1
rpy2==2.9.4
simplejson==3.16.0
jsonrpclib-pelix==0.3.1
image==1.5.24
```
Finally, pip installs DLATK version 1.1.4 by default, if you want the latest you should explicitly request it: ```$ pip install dlatk==1.1.8```. 

Best!

**Comment by ashishkab0b** [comment]
Thanks a lot @earissola! I will give this a try later when I have a bit of spare time.

**Comment by sjgiorgi** [comment]
This is helpful, thank you @earissola. 

The `dev` branch works with more recent versions of scikit-learn (tested with 0.20.2). So given the remaining dependencies are satisfied you could always clone from Github and skip the pip install.

**Comment by ashishkab0b** [comment]
That's helpful -- thanks!
