### ISSUE TITLE
conda package needs update

### ISSUE THREAD

**Issue by tslmy** [dlatk/dlatk#24]
The version hosted on [conda](https://anaconda.org/wwbp/dlatk) is old and suffers from #15 . 
Tested on Venti with an empty conda env.

I believe #15 is fixed by 4cf2aa2ff7141e34c87b16ca3feb91969e2ec758 , so a simple update should do the trick.

**Comment by izahn** [comment]
All the cool kids are on conda-forge these days, I submitted a package at https://github.com/conda-forge/staged-recipes/pull/14068

If there is anyone here who would like to be added as a co-maintainer let me know!

**Comment by izahn** [comment]
Does anyone know if the scikit-learn dependency is really 0.18.2? That's what the pypi package says, but I can't find anything in this repo corresponding to that. All I can find here is https://github.com/dlatk/dlatk/blob/public/setup.py#L97 and  https://github.com/dlatk/dlatk/blob/public/install/requirements.txt#L11 , both of which haven't  been updated in years and just say > 0.17.1

Also, if the pypi package isn't  built from here (as the different scikit-learn requirements suggest) then where is it built from? 

UPDATE: My mistake, I failed to actually read https://github.com/dlatk/dlatk/issues/15. OK, so I've skipped the windows build in https://github.com/conda-forge/staged-recipes/pull/14068 since scikit-learn < 0.20 is not available on conda-forge for that platform.

**Comment by izahn** [comment]
Pinning to scikit-learn and dropping the windows build didn't work. After reading https://github.com/dlatk/dlatk/issues/15 again and looking through the source code of the PyPi package, I think maybe the scikit-learn pinning is not needed after all. I've removed it and the package builds successfully on all platforms. If the scikit-learn pin to version 0.18.2 really is needed (for dlatk 1.1.8) please let me know before I try to release a broken conda-forge package...

**Comment by sjgiorgi** [comment]
@izahn Thanks for jumping into this. We realize that our package is very outdated and are working on merging our `dev` branch with `public` here, as well as updating pip and conda. Hopefully this will be done within the next week. I'm currently testing on more recent versions of Python and scikit-learn to make sure this release is as up to date as possible.

**Comment by izahn** [comment]
Awesome, thanks @sjgiorgi ! I will hold off on moving forward with the conda-forge submission. Again if there is anyone here willing to be a co-maintainer please let me know and I'll add you!

**Comment by izahn** [comment]
In case it helps I built a conda package for testing and uploaded it to https://anaconda.org/izahn/dlatk

The package was built from the conda recipe available at https://github.com/conda-forge/staged-recipes/pull/14068

This package currently does not impose any constraint on the `scikit-learn` version, though you may wish to do that at install time.

This snippet creates a conda environment that seems to work reasonably well (though not extensively tested!):

```
conda create -n dlatk -c conda-forge -c izahn --override-channels \
        dlatk numpy=1.16 scikit-learn=0.20.2 r-base=3.6 \
        rpy2 simplejson textstat wordcloud
```

**Comment by izahn** [comment]
Any updates here? Would love to help get this packaged in conda-forge!

**Comment by sjgiorgi** [comment]
I've updated conda, as well as pip and github. They are all in sync and include massive updates to the code base. The `setup.py` file has updated dependencies, which should now be minimal. If you are still interested in putting the package on conda-forge, please go ahead.

**Comment by izahn** [comment]
Awesome, congratulations on this release! I've resurrected the conda-forge submission at https://github.com/conda-forge/staged-recipes/pull/14068. If there is anyone here willing to serve as a co-maintainer of the conda-forge package please let me know!

**Comment by sjgiorgi** [comment]
Thank you for pushing this forward! I can be a co-maintainer.

**Comment by izahn** [comment]
Our conda-forge submission has been merged and we are live at https://github.com/conda-forge/dlatk-feedstock ! `dlatk` will be available in the conda-forge channel shortly.

**Comment by sjgiorgi** [comment]
Thanks again.
