### ISSUE TITLE
dlatkInterface.py: error: unrecognized arguments: LDA commands

### ISSUE THREAD

**Issue by andaqu** [dlatk/dlatk#28]
Running the following command to estimate LDA topics:

```
dlatkInterface.py -d <database_name> -t <table_name> -c message_id -f 'feat$1gram$<table_name>$message_id$16to16' --add_lda_messages --save_lda_files lda_files --no_lda_lexicon --mallet_path "<path>"
```
yields the following output:

```
dlatkInterface.py: error: unrecognized arguments: --estimate_lda_topics --save_lda_files lda_files --no_lda_lexicon --mallet_path <path>  
```

I am following the tutorial and checking the code at hand, it does seem that these commands do not exist in the interface.

**Comment by sjgiorgi** [comment]
We apologize but the documentation is ahead of public branch here. These commands are available in the dev branch.  We are working on getting the public branch, as well as the pip and conda installs, all in sync.

**Comment by andaqu** [comment]
> We apologize but the documentation is ahead of public branch here. These commands are available in the dev branch. We are working on getting the public branch, as well as the pip and conda installs, all in sync.

Thank you. I switched to the dev branch and the command was there.
