### ISSUE TITLE
DLATK Tutorial, Step 1

### ISSUE THREAD

**Issue by gserapio** [dlatk/dlatk#3]
When I run `dlatkInterface.py -d dla_tutorial -t msgs_xxx -c user_id --add_ngrams -n 1 --feat_occ_filter --set_p_occ 0.001 --group_freq_thresh 500`, replacing the `xxx` in `msgs_xxx` with my initials, I struggle with the following error:

```
File "/usr/bin/dlatkInterface.py", line 789
    print("Need to specify lex table with -l", file=sys.stderr)
                                                   ^
SyntaxError: invalid syntax
```

Should I be replacing user_id with something? Thanks in advance!

**Comment by sjgiorgi** [comment]
Can you post your exact command?

**Comment by gserapio** [comment]
`dlatkInterface.py -d dla_tutorial -t msgs_gsg -c user_id --add_ngrams -n 1 --feat_occ_filter --set_p_occ 0.001 --group_freq_thresh 500`

**Comment by sjgiorgi** [comment]
Your command is correct but you are trying to run Python 3 code with Python 2.

**Comment by gserapio** [comment]
Thank you so much! This is probably my problem; I will retry now.
