### ISSUE TITLE
Is python 3.9 supported?

### ISSUE THREAD

**Issue by izahn** [dlatk/dlatk#33]
I see that `dlatk` [depends on `sklearn <0.24.0`](https://github.com/dlatk/dlatk/blob/public/setup.py#L159) and that [sklearn 0.23.x only supports python 3.6-3.8](https://github.com/scikit-learn/scikit-learn/releases/tag/0.23.0)

Does that mean `dlatk` shouldn't be used with python 3.9? How much work would it take to get `dlatk` compatible with `sklearn 0.24.x` ?

**Comment by sjgiorgi** [comment]
There is already some work towards this, with a pull request from @luke-stanford . I haven't had time to review this, but I think it's mostly updated sklearn imports. My sense is that this will be fairly easy but maybe tedious. Needs to be backwards compatible.

**Comment by izahn** [comment]
Awesome, thanks! 👀

**Comment by izahn** [comment]
I grepped through the codebase for api changes listed in https://scikit-learn.org/stable/whats_new/v0.24.html#version-0-24-0

I didn't find much, maybe something in https://scikit-learn.org/stable/whats_new/v0.24.html#sklearn-naive-bayes but I don't think so. I think all the API changes are deprecations rather then removal so we should be pretty safe. I think we can safely bump the scikit-learn dependency, what do you think?

**Comment by chagag** [comment]
I am also curious about this. Any developments?

**Comment by sjgiorgi** [comment]
No developments, unfortunately, but we have put this back on our priority list and have someone working on this over the summer. I can give a more informative update when we have a better idea of how long this will take.

**Comment by sjgiorgi** [comment]
Python 3.5 through 3.9 support added with the [most recent merge](https://github.com/dlatk/dlatk/pull/44).
