### ISSUE TITLE
ImportError: No module named 'dlatk.database'

### ISSUE THREAD

**Issue by izahn** [dlatk/dlatk#34]
I've tried running  a minimal `dlatk` test but ran into this:

```
conda create -n dlatk_test -c wwbp dlatk
conda activate dlatk_test
dlatkInterface.py -h

Traceback (most recent call last):
  File "/home/izahn/.conda/envs/dlatk_test/bin/dlatkInterface.py", line 18, in <module>
    import dlatk.dlaWorker as dlaWorker
  File "/home/izahn/.conda/envs/dlatk_test/lib/python3.5/site-packages/dlatk/dlaWorker.py", line 8, in <module>
    from .database.dataEngine import DataEngine
ImportError: No module named 'dlatk.database'
```
Any ideas?

**Comment by sjgiorgi** [comment]
There was a problem with the latest pip version. I didn't include `dlatk.database` in `setup.py`. I've updated pip. Will try and update conda tomorrow.

**Comment by izahn** [comment]
Awesome thanks! I confirm that this is fixed in the latest version.  I also updated the `conda-forge` package and added a test for this in https://github.com/conda-forge/dlatk-feedstock/pull/1

**Comment by sjgiorgi** [comment]
I've updated conda to dlatk v1.2.5.
