### ISSUE TITLE
Features table names generated not consistent when extracting features with "--anscombe" switch

### ISSUE THREAD

**Issue by HuyVu0508** [dlatk/dlatk#38]
When running extracting 1 to 3-grams features with Anscombe post-process, the generated tables having inconsistent names. For example, if we run this command:
`python3 dlatkInterface.py -d database_name -t table_name -c message_id --add_ngrams -n 1 2 3 --combine_feat_tables 1to3gram --anscombe`
The generated tables will be:
`feat$1gram$table_name$message_id$16to8`
`feat$2gram$table_name$message_id$16to8`
`feat$3gram$table_name$message_id$16to8`
`feat$1to3gram$table_name$message_id`
Meaning that the `1gram`, `2gram` and `3gram` has the suffix of `$16to8`, but the `1to3gram` table does not.

**Comment by sjgiorgi** [comment]
This has been fixed.
