### ISSUE TITLE
dlatkInterface.py: error: unrecognized arguments: -g user_id

### ISSUE THREAD

**Issue by frogger** [dlatk/dlatk#45]
I am not sure if I am ok to ask this sort of question here, sorry I'm very new to this, I have been round in circles with this for ages. I am just trying to complete the Differential Language Analysis (DLA) Tutorial. When I try to run the command:

dlatkInterface.py -d dla_tutorial -t msgs_xxx -g user_id --add_ngrams -n 1 2 3 --combine_feat_tables 1to3gram

I get the error: 

dlatkInterface.py: error: unrecognized arguments: -g user_id

I think I have everything installed correctly and I have replaced msgs_ xxx with my table name. I have checked the table and the field user_id exists.

Is anyone able to see what might be going on here?

**Comment by sjgiorgi** [comment]
You are more than welcome to ask questions here! 

Can you replace `-g` with `-c`?

**Comment by frogger** [comment]
Ahhh cool that works, now getting permission problems but I’ll look into
it. Thanks!!

**Comment by sjgiorgi** [comment]
Please feel free to open another issue if you keep experiencing issues.
