### ISSUE TITLE
*MYSQL Connect ERROR on db:dla_tutorial (1045, "Access denied for user 'root'@'172.17.0.3' (using password: NO)")

### ISSUE THREAD

**Issue by frogger** [dlatk/dlatk#46]
I am having permissions problems with my databases. I have created a new user with all privileges and no password as recommended here: https://dba.stackexchange.com/questions/273751/dlatk-resolving-1045-access-denied-for-user-rootlocalhost-using-passwod

I have logged out of MySQL and logged back in as the new user but dlatk library is still trying to connect to root user

**Comment by sjgiorgi** [comment]
Can you please send your command and the full output?

You should also create the file `.my.cnf` in your home directory with your mysql username and password (as specified in the commands from the Stack Exchange page you posted):

```
[client]
user={your-mysql-username}
password={your-mysql-password}
```

Note, you should not use the curly brackets. For example, if your username was `taylorswift` and your password was `midnights` then your file would look like:

```
[client]
user=taylorswift
password=midnights
```

**Comment by frogger** [comment]
Here is my terminal output, I hope this is what you wanted..?

```
franpugh@frans-iMac ~ % docker exec -it dlatk_docker bash
root@fb8eaea0f491:/# dlatkInterface.py -d dla_tutorial -t msgs_fran -c user_id --add_ngrams -n 1 2 3 --combine_feat_tables 1to3gram
/usr/local/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/usr/local/lib/python3.6/site-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
pandas.rpy.common cannot be imported
 *MYSQL Connect ERROR on db:dla_tutorial
(1045, "Access denied for user 'root'@'172.17.0.3' (using password: NO)")
 (1 attempt)
 *MYSQL Connect ERROR on db:dla_tutorial
(1045, "Access denied for user 'root'@'172.17.0.3' (using password: NO)")
 (2 attempt)
 *MYSQL Connect ERROR on db:dla_tutorial
(1045, "Access denied for user 'root'@'172.17.0.3' (using password: NO)")
 (3 attempt)
 *MYSQL Connect ERROR on db:dla_tutorial
(1045, "Access denied for user 'root'@'172.17.0.3' (using password: NO)")
 (4 attempt)
 *MYSQL Connect ERROR on db:dla_tutorial
(1045, "Access denied for user 'root'@'172.17.0.3' (using password: NO)")
 (5 attempt)
 *MYSQL Connect ERROR on db:dla_tutorial
(1045, "Access denied for user 'root'@'172.17.0.3' (using password: NO)")
 (6 attempt)
 ```

**Comment by frogger** [comment]
I have created the file like you said, when i set up the user I did it with an empty password so do I just do this:

[client]
user=fran
password= ‘ ’

**Comment by sjgiorgi** [comment]
I'm not super familiar with Docker, but it looks like once you are in the Docker environment it switches to the `root` user as opposed to `franpugh`. 

After you run `docker exec -it dlatk_docker bash` can you open up MySQL? Try running `mysql`? Or some variation of: 

```
mysql -u fran
mysql -u fran -p
mysql -u root 
etc
```

you set this up as `fran` and not `franpugh`, I assume? First make sure you can connect to MySQL within Docker. Once you do that, make sure you have access to the proper databases by running `show databases`.

**Comment by frogger** [comment]
Yes I was using `mysql -u fran -p` to log in to mysql through Docker, show databases brings up everything.

I am guessing it is a problem with how I am running dlatk through Docker

I'll look in to it! Thank you so much for your help!

**Comment by sjgiorgi** [comment]
Try adding: `--mysql_config /Users/franpugh/.my.cnf` to your DLATK command. Use the path to your `.my.cnf` (I've assumed it's located in `/Users/franpugh`) but I could be wrong.

**Comment by frogger** [comment]
That give me this:
franpugh@frans-iMac ~ % docker exec -it dlatk_docker --mysql_config /Users/franpugh/.my.cnf bash

OCI runtime exec failed: exec failed: unable to start container process: exec: "--mysql_config": executable file not found in $PATH: unknown

But it is saved in  /Users/franpugh/

**Comment by sjgiorgi** [comment]
Please add it to your dlatk command:

```
dlatkInterface.py -d dla_tutorial -t msgs_fran -c user_id --add_ngrams -n 1 2 3 --combine_feat_tables 1to3gram --mysql_config /Users/franpugh/.my.cnf
```

**Comment by frogger** [comment]
`dlatkInterface.py -d dla_tutorial -t msgs_fran -c user_id --add_ngrams -n 1 2 3 --combine_feat_tables 1to3gram --mysql_config /Users/franpugh/.my.cnf`

Then I get this:

`dlatkInterface.py: error: unrecognized arguments: --mysql_config /Users/franpugh/.my.cnf`

**Comment by sjgiorgi** [comment]
Unfortunately, the Docker version of DLATK is out of sync with everything else (Github). We don't maintain the Docker container nor do I really know how to use Docker, so I can't really help much further without spending some more time on my end debugging. I'd recommend pulling the code from Github which has the updated arguments (`-g` and `--mysql_config`).

**Comment by frogger** [comment]
Thank you so much for your help. I’ll try pulling it from GitHub. This
library is going to be pivotal to my dissertation so I need to get it
working!! If I still have issues is it ok to post on GitHub? Thanks again
for your help today

**Comment by frogger** [comment]
Hi I have installed everything using github but I am still getting the same permissions problem

```
 *MYSQL Connect ERROR on db:dla_tutorial
(1044, "Access denied for user 'franpugh'@'localhost' to database 'dla_tutorial'")
```
I have tried:

`GRANT ALL PRIVILEGES ON *.* TO 'franpugh'@'%';
`
But I still can't get it to work

**Comment by frogger** [comment]
I have figured it out now, thanks
