### ISSUE TITLE
Installation issues GitHub pull

### ISSUE THREAD

**Issue by frogger** [dlatk/dlatk#47]
I am having trouble installing this via github pull. I think I installed the dependencies correctly. This is my terminal output, sorry there is loads of it but I wasn't sure what was relevant:

Last login: Fri Jan 20 00:03:41 on ttys001
franpugh@frans-iMac ~ % git clone https://github.com/dlatk/dlatk.git
Cloning into 'dlatk'...
remote: Enumerating objects: 4890, done.
remote: Counting objects: 100% (711/711), done.
remote: Compressing objects: 100% (293/293), done.
remote: Total 4890 (delta 465), reused 653 (delta 418), pack-reused 4179
Receiving objects: 100% (4890/4890), 28.19 MiB | 9.98 MiB/s, done.
Resolving deltas: 100% (3458/3458), done.
franpugh@frans-iMac ~ % cd dlatk
franpugh@frans-iMac dlatk % python3 setup.py install
running install
running bdist_egg
running egg_info
creating dlatk.egg-info
writing dlatk.egg-info/PKG-INFO
writing dependency_links to dlatk.egg-info/dependency_links.txt
writing requirements to dlatk.egg-info/requires.txt
writing top-level names to dlatk.egg-info/top_level.txt
writing manifest file 'dlatk.egg-info/SOURCES.txt'
reading manifest file 'dlatk.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'RELEASE.md'
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '#*' found anywhere in distribution
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
warning: no previously-included files matching '*__pycache__*' found anywhere in distribution
adding license file 'LICENSE'
writing manifest file 'dlatk.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-universal2/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/dlatk
copying dlatk/autoencoders.py -> build/lib/dlatk
copying dlatk/dimensionReducer.py -> build/lib/dlatk
copying dlatk/messageAnnotator.py -> build/lib/dlatk
copying dlatk/featureExtractor.py -> build/lib/dlatk
copying dlatk/pca_mod.py -> build/lib/dlatk
copying dlatk/dlaConstants.py -> build/lib/dlatk
copying dlatk/dlaWorker.py -> build/lib/dlatk
copying dlatk/outcomeAnalyzer.py -> build/lib/dlatk
copying dlatk/textCleaner.py -> build/lib/dlatk
copying dlatk/classifyPredictor.py -> build/lib/dlatk
copying dlatk/featureRefiner.py -> build/lib/dlatk
copying dlatk/semanticsExtractor.py -> build/lib/dlatk
copying dlatk/wrappedPCA.py -> build/lib/dlatk
copying dlatk/outcomeGetter.py -> build/lib/dlatk
copying dlatk/__init__.py -> build/lib/dlatk
copying dlatk/featureStar.py -> build/lib/dlatk
copying dlatk/featureGetter.py -> build/lib/dlatk
copying dlatk/occurrenceSelection.py -> build/lib/dlatk
copying dlatk/topicExtractor.py -> build/lib/dlatk
copying dlatk/DDLA.py -> build/lib/dlatk
copying dlatk/mediation.py -> build/lib/dlatk
copying dlatk/messageTransformer.py -> build/lib/dlatk
copying dlatk/regressionPredictor.py -> build/lib/dlatk
creating build/lib/dlatk/database
copying dlatk/database/query.py -> build/lib/dlatk/database
copying dlatk/database/__init__.py -> build/lib/dlatk/database
copying dlatk/database/dataEngine.py -> build/lib/dlatk/database
creating build/lib/dlatk/lib
copying dlatk/lib/wc_tools.py -> build/lib/dlatk/lib
copying dlatk/lib/happierfuntokenizing.py -> build/lib/dlatk/lib
copying dlatk/lib/__init__.py -> build/lib/dlatk/lib
copying dlatk/lib/wordcloud.py -> build/lib/dlatk/lib
copying dlatk/lib/TweetNLP.py -> build/lib/dlatk/lib
copying dlatk/lib/StanfordParser.py -> build/lib/dlatk/lib
copying dlatk/lib/descStats.py -> build/lib/dlatk/lib
creating build/lib/dlatk/lexicainterface
copying dlatk/lexicainterface/lexInterface.py -> build/lib/dlatk/lexicainterface
copying dlatk/lexicainterface/__init__.py -> build/lib/dlatk/lexicainterface
creating build/lib/dlatk/mysqlmethods
copying dlatk/mysqlmethods/__init__.py -> build/lib/dlatk/mysqlmethods
copying dlatk/mysqlmethods/mysqlMethods.py -> build/lib/dlatk/mysqlmethods
copying dlatk/mysqlmethods/mysql_iter_funcs.py -> build/lib/dlatk/mysqlmethods
creating build/lib/dlatk/sqlitemethods
copying dlatk/sqlitemethods/__init__.py -> build/lib/dlatk/sqlitemethods
copying dlatk/sqlitemethods/sqliteMethods.py -> build/lib/dlatk/sqlitemethods
creating build/lib/dlatk/tools
copying dlatk/tools/__init__.py -> build/lib/dlatk/tools
copying dlatk/tools/importmethods.py -> build/lib/dlatk/tools
creating build/lib/dlatk/data
copying dlatk/data/dla_tutorial.sql -> build/lib/dlatk/data
copying dlatk/data/dlatk_lexica.sql -> build/lib/dlatk/data
copying dlatk/tools/colabify.sh -> build/lib/dlatk/tools
copying dlatk/lib/meloche_bd.ttf -> build/lib/dlatk/lib
copying dlatk/lib/oval_big_mask.png -> build/lib/dlatk/lib
copying dlatk/lib/oval_mask.png -> build/lib/dlatk/lib
creating build/bdist.macosx-10.9-universal2
creating build/bdist.macosx-10.9-universal2/egg
creating build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/autoencoders.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/dimensionReducer.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
creating build/bdist.macosx-10.9-universal2/egg/dlatk/database
copying build/lib/dlatk/database/query.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/database
copying build/lib/dlatk/database/__init__.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/database
copying build/lib/dlatk/database/dataEngine.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/database
copying build/lib/dlatk/messageAnnotator.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/featureExtractor.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/pca_mod.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
creating build/bdist.macosx-10.9-universal2/egg/dlatk/tools
copying build/lib/dlatk/tools/colabify.sh -> build/bdist.macosx-10.9-universal2/egg/dlatk/tools
copying build/lib/dlatk/tools/__init__.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/tools
copying build/lib/dlatk/tools/importmethods.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/tools
copying build/lib/dlatk/dlaConstants.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/dlaWorker.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/outcomeAnalyzer.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/textCleaner.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/classifyPredictor.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/featureRefiner.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/semanticsExtractor.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/wrappedPCA.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/outcomeGetter.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/__init__.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/featureStar.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/featureGetter.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
creating build/bdist.macosx-10.9-universal2/egg/dlatk/mysqlmethods
copying build/lib/dlatk/mysqlmethods/__init__.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/mysqlmethods
copying build/lib/dlatk/mysqlmethods/mysqlMethods.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/mysqlmethods
copying build/lib/dlatk/mysqlmethods/mysql_iter_funcs.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/mysqlmethods
copying build/lib/dlatk/occurrenceSelection.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/topicExtractor.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/DDLA.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/mediation.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
creating build/bdist.macosx-10.9-universal2/egg/dlatk/lib
copying build/lib/dlatk/lib/wc_tools.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/lib
copying build/lib/dlatk/lib/happierfuntokenizing.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/lib
copying build/lib/dlatk/lib/__init__.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/lib
copying build/lib/dlatk/lib/wordcloud.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/lib
copying build/lib/dlatk/lib/meloche_bd.ttf -> build/bdist.macosx-10.9-universal2/egg/dlatk/lib
copying build/lib/dlatk/lib/TweetNLP.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/lib
copying build/lib/dlatk/lib/StanfordParser.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/lib
copying build/lib/dlatk/lib/oval_mask.png -> build/bdist.macosx-10.9-universal2/egg/dlatk/lib
copying build/lib/dlatk/lib/descStats.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/lib
copying build/lib/dlatk/lib/oval_big_mask.png -> build/bdist.macosx-10.9-universal2/egg/dlatk/lib
creating build/bdist.macosx-10.9-universal2/egg/dlatk/lexicainterface
copying build/lib/dlatk/lexicainterface/lexInterface.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/lexicainterface
copying build/lib/dlatk/lexicainterface/__init__.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/lexicainterface
copying build/lib/dlatk/messageTransformer.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
copying build/lib/dlatk/regressionPredictor.py -> build/bdist.macosx-10.9-universal2/egg/dlatk
creating build/bdist.macosx-10.9-universal2/egg/dlatk/data
copying build/lib/dlatk/data/dla_tutorial.sql -> build/bdist.macosx-10.9-universal2/egg/dlatk/data
copying build/lib/dlatk/data/dlatk_lexica.sql -> build/bdist.macosx-10.9-universal2/egg/dlatk/data
creating build/bdist.macosx-10.9-universal2/egg/dlatk/sqlitemethods
copying build/lib/dlatk/sqlitemethods/__init__.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/sqlitemethods
copying build/lib/dlatk/sqlitemethods/sqliteMethods.py -> build/bdist.macosx-10.9-universal2/egg/dlatk/sqlitemethods
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/autoencoders.py to autoencoders.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/dimensionReducer.py to dimensionReducer.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/database/query.py to query.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/database/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/database/dataEngine.py to dataEngine.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/messageAnnotator.py to messageAnnotator.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/featureExtractor.py to featureExtractor.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/pca_mod.py to pca_mod.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/tools/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/tools/importmethods.py to importmethods.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/dlaConstants.py to dlaConstants.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/dlaWorker.py to dlaWorker.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/outcomeAnalyzer.py to outcomeAnalyzer.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/textCleaner.py to textCleaner.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/classifyPredictor.py to classifyPredictor.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/featureRefiner.py to featureRefiner.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/semanticsExtractor.py to semanticsExtractor.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/wrappedPCA.py to wrappedPCA.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/outcomeGetter.py to outcomeGetter.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/featureStar.py to featureStar.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/featureGetter.py to featureGetter.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/mysqlmethods/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/mysqlmethods/mysqlMethods.py to mysqlMethods.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/mysqlmethods/mysql_iter_funcs.py to mysql_iter_funcs.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/occurrenceSelection.py to occurrenceSelection.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/topicExtractor.py to topicExtractor.cpython-310.pyc
build/bdist.macosx-10.9-universal2/egg/dlatk/topicExtractor.py:300: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(estimate_topics, "pyMallet not installed.")
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/DDLA.py to DDLA.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/mediation.py to mediation.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/lib/wc_tools.py to wc_tools.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/lib/happierfuntokenizing.py to happierfuntokenizing.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/lib/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/lib/wordcloud.py to wordcloud.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/lib/TweetNLP.py to TweetNLP.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/lib/StanfordParser.py to StanfordParser.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/lib/descStats.py to descStats.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/lexicainterface/lexInterface.py to lexInterface.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/lexicainterface/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/messageTransformer.py to messageTransformer.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/regressionPredictor.py to regressionPredictor.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/sqlitemethods/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/dlatk/sqlitemethods/sqliteMethods.py to sqliteMethods.cpython-310.pyc
creating build/bdist.macosx-10.9-universal2/egg/EGG-INFO
installing scripts to build/bdist.macosx-10.9-universal2/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.10
copying and adjusting dlatkInterface.py -> build/scripts-3.10
changing mode of build/scripts-3.10/dlatkInterface.py from 644 to 755
creating build/bdist.macosx-10.9-universal2/egg/EGG-INFO/scripts
copying build/scripts-3.10/dlatkInterface.py -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO/scripts
changing mode of build/bdist.macosx-10.9-universal2/egg/EGG-INFO/scripts/dlatkInterface.py to 755
copying dlatk.egg-info/PKG-INFO -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying dlatk.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying dlatk.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying dlatk.egg-info/requires.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying dlatk.egg-info/top_level.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
dlatk.__pycache__.dlaConstants.cpython-310: module references __file__
dlatk.__pycache__.topicExtractor.cpython-310: module references __file__
dlatk.lexicainterface.__pycache__.lexInterface.cpython-310: module references __file__
dlatk.lib.__pycache__.wordcloud.cpython-310: module references __file__
dlatk.tools.__pycache__.importmethods.cpython-310: module references __file__
creating dist
creating 'dist/dlatk-1.2.6-py3.10.egg' and adding 'build/bdist.macosx-10.9-universal2/egg' to it
removing 'build/bdist.macosx-10.9-universal2/egg' (and everything under it)
Processing dlatk-1.2.6-py3.10.egg
removing '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dlatk-1.2.6-py3.10.egg' (and everything under it)
creating /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dlatk-1.2.6-py3.10.egg
Extracting dlatk-1.2.6-py3.10.egg to /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dlatk-1.2.6-py3.10.egg/dlatk/topicExtractor.py:300: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(estimate_topics, "pyMallet not installed.")
dlatk 1.2.6 is already the active version in easy-install.pth
Installing dlatkInterface.py script to /Library/Frameworks/Python.framework/Versions/3.10/bin

Installed /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dlatk-1.2.6-py3.10.egg
Processing dependencies for dlatk==1.2.6
Searching for statsmodels<=0.13.2,>=0.5.0
Reading https://pypi.org/simple/statsmodels/
Download error on https://pypi.org/simple/statsmodels/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997) -- Some packages may not be found!
Couldn't retrieve index page for 'statsmodels'
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997) -- Some packages may not be found!
No local packages or working download links found for statsmodels<=0.13.2,>=0.5.0
error: Could not find suitable distribution for Requirement.parse('statsmodels<=0.13.2,>=0.5.0')
franpugh@frans-iMac dlatk % python3 dlatkInterface.py -h

Warning: unable to import nltk.tree or nltk.corpus or nltk.data
Warning: unable to import jsonrpclib or simplejson
LexInterface:warning: nltk.corpus module not imported.
Warning: Cannot import langid (cannot use addLanguageFilterTable)
warning: unable to import nltk.tree or nltk.corpus or nltk.data
Traceback (most recent call last):
  File "/Users/franpugh/dlatk/dlatkInterface.py", line 36, in <module>
    from dlatk.regressionPredictor import RegressionPredictor, CombinedRegressionPredictor, ClassifyToRegressionPredictor
  File "/Users/franpugh/dlatk/dlatk/regressionPredictor.py", line 23, in <module>
    from collections import defaultdict, Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
franpugh@frans-iMac dlatk %

**Comment by hschwartz** [comment]
Seems to be due to using python 3.10 which dlatk is not yet compatible.
Can you revert to python 3.7 (should work up to 3.9 but less tested for
that). Otherwise, it will probably be a few months until it is updated to
be compatible with 3.10.

**Comment by frogger** [comment]
Thanks. I set up a conda environment for Python 3.7 and the install said use 3.8 so I did that. No when I try to run the command:

`dlatkInterface.py -d dla_tutorial -t msgs_xxx -g user_id --add_ngrams -n 1 2 3 --combine_feat_tables 1to3gram`

I get the following output. I apologise for my ignorance but I'm really new to this:

(python3.8) franpugh@frans-iMac dlatk % dlatkInterface.py -d dla_tutorial -t msgs_fran -g user_id --add_ngrams -n 1 2 3 --combine_feat_tables 1to3gram
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (statsmodels 0.13.5 (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages), Requirement.parse('statsmodels<=0.13.2,>=0.5.0'), {'dlatk'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/dlatkInterface.py", line 4, in <module>
    __import__('pkg_resources').run_script('dlatk==1.2.6', 'dlatkInterface.py')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'statsmodels<=0.13.2,>=0.5.0' distribution was not found and is required by dlatk

**Comment by hschwartz** [comment]
The specific error is you need a statsmodels package between versions 0.5.0
and 0.13.2. From within your environment, you can do the following to make
sure you have all of the library requirements:

wget https://github.com/dlatk/dlatk/blob/public/install/requirements.sys
xargs apt-get install < requirements.sys


However, the error lines also seems to indicate it's still looking under
python 3.10("*Versions/3.10/lib/python3.10/site-packages/*")so you may
still have other errors after you do that. My guess is you weren't running
dlatkInferface from within the conda environment.

**Comment by frogger** [comment]
when I use 
`xargs apt-get install < requirements.sys`
I get the error
`xargs: unterminated quote
`
I am definitely running from within the environment

`(python3.8) franpugh@frans-iMac dlatk %   `

**Comment by frogger** [comment]
I have figured it out now, thanks
