### ISSUE TITLE
Better installation instructions--particularly for Docker

### ISSUE THREAD

**Issue by tyarkoni** [dlatk/dlatk#6]
Given that most if not all of the audience for this package is likely to consist of scientists without a strong scientific computing background, it would be helpful to improve the docs--particularly with respect to the Docker container. [This twitter thread](https://twitter.com/talyarkoni/status/985267798766243840) may be instructive.

**Comment by sjgiorgi** [comment]
Can you be more specific about what is confusing or missing? Or what would make this easier? This is something we've spent a lot of time thinking about and would love to make the install process more streamlined. 

The Docker container was made by another developer and isn't currently maintained by our group. This will change in the future but we've assumed that Docker would be the most foreign to the non-CS audience (as compared to pip or conda).

**Comment by sjgiorgi** [comment]
Full Docker installation instructions are available [here](http://dlatk.wwbp.org/tutorials/tut_docker.html). The DLATK Docker container is hosted at [DockerHub](https://hub.docker.com/r/dlatk/dlatk/) so install should be pretty painless. 

Thank you for the feedback.
