### ISSUE TITLE
Working with pre-tokenised and tagged data

### ISSUE THREAD

**Issue by olsgaard** [dlatk/dlatk#7]
Is it possible to load a pre-tokenised and tagged dataset into DLATK?

I'm guessing I would have to build my own mysql table, but looking at [Tokenization, Part of Speech Tagging and Segmentation tutorial](http://dlatk.wwbp.org/tutorials/tut_text_transformations.html) I am having a hard time understanding how such a table (tables?) should be laid out.

**Comment by sjgiorgi** [comment]
It depends what you want to do. You can create a feature table (most common use case) or a tokenized table. If you look at [the feature extraction tutorial](http://dlatk.wwbp.org/tutorials/tut_adv_fe.html) you can see that every feature table has the same structure. For example: 

```
+----+----------+-----------+-------+----------------------+
| id | group_id | feat      | value | group_norm           |
+----+----------+-----------+-------+----------------------+
|  1 |    28451 | wonderful |     1 | 0.000953288846520496 |
|  2 |    28451 | let       |     1 | 0.000953288846520496 |
|  3 |    28451 | promotion |     1 | 0.000953288846520496 |
|  4 |    28451 | assured   |     1 | 0.000953288846520496 |
|  5 |    28451 | lime      |     1 | 0.000953288846520496 |
+----+----------+-----------+-------+----------------------+
```

Every table needs a `group_id`, `feat`, `value` and `group_norm` column. These tables are used in correlation, prediction/classification, etc. type tasks. [This tutorial](http://dlatk.wwbp.org/tutorials/tut_feat_tables.html) explains the structure and naming conventions. 

The tokenized tables (listed in the [Tokenization, Part of Speech Tagging and Segmentation](http://dlatk.wwbp.org/tutorials/tut_text_transformations.html#tokenization) tutorial) are used in less common features. They are typically used to derive feature tables (as above) or when running [LDA](http://dlatk.wwbp.org/tutorials/tut_lda.html). 

Feel free to post examples of your data and I can help you create the proper table.

**Comment by olsgaard** [comment]
That is very kind of you.

My current data frame has form and content like 

| doc_id|Surface form |reading  |Coarse POS |
|-------:|:------------|:--------|:----------|
|       1|へえ         |へえ     |感動詞     |
|       1|、           |、       |特殊       |
|       1|すごい       |すごい   |形容詞     |
|       1|ね           |ね       |助詞       |
|       1|。           |。       |特殊       |
|       1|秘密         |ひみつ   |形容詞     |
|       1|基地         |きち     |名詞       |
|       1|みたいだ     |みたいだ |助動詞     |
|       1|な           |な       |助詞       |
|       2|お           |お       |接頭辞     |
|       2|父さん       |とうさん |名詞       |
|       2|、           |、       |特殊       |
|       2|メイ         |めい     |名詞       |
|       2|、           |、       |特殊       |
|       2|ここ         |ここ     |指示詞     |
|       2|で           |で       |助詞       |
|       2|トトロ       |トトロ   |名詞       |
|       2|に           |に       |助詞       |
|       2|あった       |あった   |動詞       |
|       2|んだ         |んだ     |助動詞     |
|       2|って         |って     |助詞       |

And then I have a secondary list that links `doc_id`s to *target values*.  I'm interested in exploring which words correlate to the target, but also if tense and other syntactical features have an effect.

Looking at the feature table definition, it should in this case look something like this for surface_form:

| id| group_id|feat     | value| group_norm|
|--:|--------:|:--------|-----:|----------:|
|  1|        1|、       |     1|  0.1111111|
|  2|        1|。       |     1|  0.1111111|
|  3|        1|すごい   |     1|  0.1111111|
|  4|        1|な       |     1|  0.1111111|
|  5|        1|ね       |     1|  0.1111111|
|  6|        1|へえ     |     1|  0.1111111|
|  7|        1|みたいだ |     1|  0.1111111|
|  8|        1|基地     |     1|  0.1111111|
|  9|        1|秘密     |     1|  0.1111111|
|  1|        2|、       |     2|  0.1666667|
|  2|        2|あった   |     1|  0.0833333|
|  3|        2|お       |     1|  0.0833333|
|  4|        2|ここ     |     1|  0.0833333|
|  5|        2|って     |     1|  0.0833333|
|  6|        2|で       |     1|  0.0833333|
|  7|        2|に       |     1|  0.0833333|
|  8|        2|んだ     |     1|  0.0833333|
|  9|        2|トトロ   |     1|  0.0833333|
| 10|        2|メイ     |     1|  0.0833333|
| 11|        2|父さん   |     1|  0.0833333|

And this for coarse_POS

| id| group_id|feat   | value| group_norm|
|--:|--------:|:------|-----:|----------:|
|  1|        1|助動詞 |     1|  0.1111111|
|  2|        1|助詞   |     2|  0.2222222|
|  3|        1|名詞   |     1|  0.1111111|
|  4|        1|形容詞 |     2|  0.2222222|
|  5|        1|感動詞 |     1|  0.1111111|
|  6|        1|特殊   |     2|  0.2222222|
|  1|        2|助動詞 |     1|  0.0833333|
|  2|        2|助詞   |     3|  0.2500000|
|  3|        2|動詞   |     1|  0.0833333|
|  4|        2|名詞   |     3|  0.2500000|
|  5|        2|指示詞 |     1|  0.0833333|
|  6|        2|接頭辞 |     1|  0.0833333|
|  7|        2|特殊   |     2|  0.1666667|

**Comment by sjgiorgi** [comment]
Besides the `id` column everything else looks good. Typically we use `id` as an auto-incremented (primary) key. I don't think that column is necessary. Tables created using DLATK will add this column but I often use feature tables with only `group_id`, `feat`, `value` and `group_norm`, so you might be okay. 

Looking ahead, take note of the [--group_freq_thresh](http://dlatk.wwbp.org/fwinterface/fwflag_group_freq_thresh.html) flag. This is the minimum word frequency needed for your `group_id` to be considered in the analysis and is typically set to 500 as a default. To turn it off just set `--group_freq_thresh 0` and make sure your `doc_id` don't contain empty text.

**Comment by olsgaard** [comment]
@sjgiorgi , thank you very much for your help. I've been hacking around hand-building these tables, and there is a lot to take into account, which made me wonder: 

Would it be easier to simply build a "CSV-tokenizer/tagger"? Or are the current tokenizers/taggers hardcoded?

**Comment by sjgiorgi** [comment]
Agreed, please let us know if you have suggestions on how to make the package more user friendly. While there is a lot to take in at first we think it is worth the effort in the long run. 

We've shared our tokenizer [here](https://github.com/dlatk/happierfuntokenizing). Should be simple to tokenize a csv but let me know if you need help setting it up.
