### ISSUE TITLE
Issue with generating word cloud and generating pickle file

### ISSUE THREAD

**Issue by icybear1990** [dlatk/dlatk#8]
Hi,
I came across this dlatk toolkit recently and i have been trying it out but i met with some issues
I have a sample dataset of around 500k records, i wished to achieve the final result of the lexical json by appending new words to your current lexical json 
however after i executed this command to generate the world cloud file:

py dlatkInterface.py -d databasename -t msgs -c user_id -f feat$1to3gram$msgs$user_id$16to16 --outcome_table databasename --group_freq_thresh 0 --outcomes personality_n --output_name xxx_output --tagcloud --make_wordcloud

it returned the error of sql server ran away after it ran for a few days of finding the correlations.

the default value for the --group-freq_thresh should be set to 500 accordingly to your tutorial however, it kept returning error and being unable to proceed until i changed the threshold value to 0.

Then i proceeded to executing this step

1) dlatkInterface.py -d testing -t msgs -c user_id --f feat$1gram$messages_en$user_id$16to16$0_01 --outcome_table databasetable --outcomes personality_n --train_regression --save_model --picklefile new.pickle

this command returns an error of
Error: Found array with 0 sample(s) (shape=(0, 1994) while a minimum of 1 required by StandardScaler

then i tried this command too:

dlatkInterface.py -d testing -t msgs -c user_id -f 'feat$cat_met_a30_2000_cp_w$msgs$user_id$16to16' 'feat$1gram$msgs$user_id$16to16' --outcome_table databasetable --group_freq_thresh 500 --outcomes personality_o --output_name xxx_personality_o_output --combo_test_reg --model ridgecv --folds 10

it returned an error of range() arg 3 must not be zero

Weird thing is i have already clean up dirty data and removed records with outliers records(where all the personality o , c , e , a , n returns 0 value thus it should be able to find the correlation

May i know how do i go about resolving this?

I also tried extracting 100 records as a subset out of the 500k records, i am able to generate a txt file for the wordcloud but i am unable to generate the image for the word cloud as seen in your tutorial, however when i tried to run the command to generate the pickle file , the same error persist.

**Comment by sjgiorgi** [comment]
It seems like these queries are too large for your MySQL settings. Two tips that could help the timeout issues:

1. Use a feature occurrence filter on your 1to3gram table using the [--feat_occ_filter](http://dlatk.wwbp.org/fwinterface/fwflag_feat_occ_filter.html) flag. This is good practice in general. As an additional filter you could run the [--feat_colloc_filter](http://dlatk.wwbp.org/fwinterface/fwflag_feat_colloc_filter.html) flag to filter 2 and 3grams based on a PMI threshold. I typically run this using the default settings. It works well when running DLA (what you are trying to run here) but doesn't help much in prediction tasks. 
2. You could create a new outcome table `databasetable_500` and only include users that meet the 500 word threshold. To find each users word total you can run the sql query: `select group_id, sum(value) from feat$1gram$msgs$user_id$16to16 group by group_id`. Once you have the `databasetable_500` table then you should set `--group_freq_thresh 0`. 

For your other errors (`...Found array with 0 sample...`) it's probably filtering by the default group frequency threshold (500) and removing all of your users. If you can post the complete output I can help debug.
