### ISSUE TITLE
Issue Generating wordcloud using amueller algorithm

### ISSUE THREAD

**Issue by ashleygw** [dlatk/dlatk#9]
Wordcloud.py has updated their generate_from_frequencies() method to take a dict, rather than a list of tuples. Currently when trying to build a wordcloud using this algorithm I get the error" AttributeError: 'list' object has no attribute 'items'", which is reflected in this issue:
https://github.com/amueller/word_cloud/issues/291

This is fixed by replacing word_freq_tup with a dictionary, then passing that dictionary to the generate_from_frequencies() method when the wordcloud is built.

Another issue I ran into was with choosing a font when building the cloud. I'm running Linux Mint and initially got the error "cannot open resource" when trying to build the cloud. As a temporary fix, I replaced the file_path=file_path with an actual path to a font throughout the file.

**Comment by sjgiorgi** [comment]
We us an older version of wordcloud, please use version 1.1.3.
